import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/components/providers/query-provider";
import { cn } from "@/lib/utils";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={cn(
                "h-full antialiased",
                geistSans.variable,
                geistMono.variable,
                inter.variable,
                "font-sans"
            )}
        >
            <TooltipProvider>
                <body className="min-h-screen bg-background font-sans antialiased">
                    <QueryProvider>
                        {/* Убрали mx-auto отсюда, добавили w-full */}
                        <div className="relative flex min-h-screen flex-col">
                            <Header />
                            <main className="flex-1 w-full">
                                {children}
                            </main>
                            <Footer />
                        </div>
                        <Toaster position="top-right" richColors />
                    </QueryProvider>
                </body>
            </TooltipProvider>

        </html>
    );
}
